// Generated by Claude: https://claude.ai/chat/e05980ff-3152-4e54-8500-b6134312b416
// Reviewed and modified for later reuse by Hyounjun Chang

/*
 * main.c — Example: play an MP3 in the background while doing other work
 *
 * Usage: ./mp3_player_demo [-d <device>] <file.mp3>
 *
 *   -d <device>  ALSA device to use, e.g. hw:2,0 (run `aplay -l` to list)
 *                Defaults to system default if not specified.
 *
 * Controls (press Enter after each key):
 *   p — pause
 *   r — resume
 *   q — quit
 */

#include "mp3_player.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static void usage(const char *prog)
{
    fprintf(stderr, "Usage: %s [-d <device>] <file.mp3>\n", prog);
    fprintf(stderr, "  -d <device>  ALSA device (e.g. hw:2,0). Run `aplay -l` to list.\n");
}

int main(int argc, char *argv[])
{
    const char *device = NULL;
    const char *file   = NULL;

    /* Parse arguments */
    for (int i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-d") == 0) {
            if (i + 1 >= argc) {
                fprintf(stderr, "Error: -d requires a device argument\n");
                usage(argv[0]);
                return 1;
            }
            device = argv[++i];
        } else if (argv[i][0] == '-') {
            fprintf(stderr, "Error: unknown option '%s'\n", argv[i]);
            usage(argv[0]);
            return 1;
        } else {
            file = argv[i];
        }
    }

    if (!file) {
        usage(argv[0]);
        return 1;
    }

    mp3_player_t *player = mp3_player_create();
    if (!player) {
        fprintf(stderr, "Failed to create player\n");
        return 1;
    }

    if (device) {
        mp3_player_set_device(player, device);
        printf("Audio device: %s\n", device);
    }

    printf("Starting background playback of: %s\n", file);

    if (mp3_player_play(player, file) != 0) {
        fprintf(stderr, "Failed to start playback\n");
        mp3_player_destroy(player);
        return 1;
    }

    printf("Controls: [p] pause  [r] resume  [q] quit\n");

    int ch;
    while ((ch = getchar()) != EOF) {
        if (ch == '\n') continue;

        switch (ch) {
        case 'p':
            mp3_player_pause(player);
            printf("Paused at %02d:%02d\n",
                   (int)mp3_player_get_position(player) / 60,
                   (int)mp3_player_get_position(player) % 60);
            break;
        case 'r':
            mp3_player_resume(player);
            printf("Resumed\n");
            break;
        case 'q':
            mp3_player_stop(player);
            goto done;
        default:
            printf("Unknown command. Controls: [p] pause  [r] resume  [q] quit\n");
            break;
        }

        if (!mp3_player_is_playing(player)) {
            printf("Playback finished.\n");
            break;
        }
    }

done:
    mp3_player_destroy(player);
    return 0;
}
